module.exports = {
	preset: 'ts-jest',
	testEnvironment: 'jsdom',
	setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
	moduleNameMapper: {
		'^@utils/(.*)$': '<rootDir>/src/utils/$1',
		'^@components/(.*)$': '<rootDir>/src/components/$1',
		'^@services/(.*)$': '<rootDir>/src/services/$1',
		'\\.(css|less|scss|sass)$': 'identity-obj-proxy',
	},
	transform: {
		'^.+\\.(ts|tsx)$': 'ts-jest',
		'^.+\\.(js|jsx)$': 'babel-jest',
	},
	testMatch: [
		'<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
		'<rootDir>/src/**/*.{test,spec}.{js,jsx,ts,tsx}',
	],
	testPathIgnorePatterns: [
		'/node_modules/',
		'/__tests__/mocks/',
		'/__tests__/fixtures/',
		'/__tests__/utils/',
		'/types/',
		'/src/types/',
		'\\.helper\\.tsx$',
		'\\.fixture\\.ts$',
		'/__tests__/types/',
		'/__tests__/contexts/MockTaskProvider.tsx',
		'/src/utils/format.ts',
	],
	coveragePathIgnorePatterns: [
		'/__tests__/',
		'\\.helper\\.tsx$',
		'\\.fixture\\.ts$',
		'/types/',
		'/src/types/',
		'/__tests__/types/',
		'/__tests__/contexts/MockTaskProvider.tsx',
		'/src/utils/format.ts',
	],
	collectCoverageFrom: [
		'src/**/*.{js,jsx,ts,tsx}',
		'!src/**/*.d.ts',
		'!src/index.tsx',
		'!src/reportWebVitals.ts',
		'!src/__tests__/utils/format.test.ts',
		'!src/components/index.ts',
	],
	coverageDirectory: 'coverage',
	coverageReporters: ['text', 'lcov', 'html'],
	testEnvironmentOptions: {
		resources: 'usable',
		url: 'http://localhost',
	},
};
